name: Periodic Health Check

on: 
  workflow_dispatch: 
  schedule:
  # at tue, september, 8th, at 10:45am and 10:56am
    - cron: '45,56 10 8 9 2'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello'